### ISSUE TITLE
User specific XDT for .pentia folder

### ISSUE THREAD

**Issue by Hafeok** [PentiaLabs/WebSolutionBuildScripts#176]
As a user i want to apply user specific configuration setting to the WebSolution without checking them into VCS. 

I thinking that we might add a way to have an App_Config folder in the .pentia folder where user specific XDT transforms are placed, that be applied in the end.

**Comment by uli-weltersbach** [comment]
@Hafeok : Could you provide a concrete use case for this?

**Comment by uli-weltersbach** [comment]
Skipped until further notice.
