### ISSUE TITLE
Improve error output when PowerShellGet can't find a package

### ISSUE THREAD

**Issue by Hafeok** [PentiaLabs/WebSolutionBuildScripts#177]
When using a solution with a runtime-dependencies.config, the newest version cant find the packages.

Check the commit e4f9fd08b2ab393ae4cd1c5c085c0bfaf4984520  on HusCompagniet.

**Comment by uli-weltersbach** [comment]
As the use of runtime-dependencies.config and PowerShellGet is deprecated, fixing this is a low priority.
