### ISSUE TITLE
Make Get-MSBuild more robust

### ISSUE THREAD

**Issue by uli-weltersbach** [PentiaLabs/WebSolutionBuildScripts#189]
Using the module `VSSetup` as a dependency for `Get-MSBuild` would allow MSBuild Tools 15+ to be found correctly, which `hMSBuild.bat` currently doesn't. 

See https://github.com/Microsoft/vssetup.powershell. 

The logic would be to use `Get-VSSetupInstance -All` to find the latest installed build tools (v15+), then fall back to `hMSBuild.bat` to find v14 and lower.

**Comment by istern** [comment]
This is solved from vs2019 and forward
