### ISSUE TITLE
Optional parameter to not clean the $WebrootOutputPath in Publish-UnconfiguredWebSolution 

### ISSUE THREAD

**Issue by melker** [PentiaLabs/WebSolutionBuildScripts#217]
We have been experimenting and realized that it is much simpler and easier to maintain and upgrade if we, when deploying, make a SIF deploy, site content only, of the SitecoreCM and SitecoreCD sites. The we deploy our code and run transforms.  

I.e. we do not need to build and maintain (2 sepearate) nuget packages of sitecores code and config, we just yse the SIF-packages from Sitecores site.

The problem related to this code is that the Publish-UnconfiguredWebSolution always cleans the Webroot. I.e.x removing the SIF installed code/config.

To solve this I would like some optional parameter all the way in) to not do this cleaning:

    Write-Progress -Activity "Publishing web solution" -Status "Cleaning webroot output path"
    Remove-WebrootOutputPath -WebrootOutputPath $WebrootOutputPath

PS: If you are concerned about the speed of setting up the web folder using SIF the simplified deployment of SIF takes about 5 seconds (if almost updated) and up to a maximum 30 seconds (for a fresh install in empty folder).

PPS: I will solve it for now by making Publish-UnconfiguredWebSolution deploy to a temporary folder and them making the merge with the SIF deploy webroot with a move/copy command but it would be better to apply it directly.

**Comment by istern** [comment]
This sounds like a great idea can you make a pull request with the changes for us to review.
